- name: exam
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    - name: Update APT Package repository cache
      apt:
         update_cache: True    

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
         name: 
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    - name: Install dependencies for Docker
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Update servers
      apt:
        update_cache: yes

    - name: Install dependencies for docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Add user ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      become: yes        

    - name: Download Compose the Latest Docker Version
      shell: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose'

    - name: Install python module
      apt: 
        name: 
          - python3
          - python3-docker
          - python3-distutils
          - python3-pip
        update_cache: yes
        state: present

    - name: Install pip python & docker
      shell: 'pip install docker-compose'

    - name: Install python docker / docker-compose module
      pip:
        name:
          - docker
          - docker-compose

