name: 'Ansible'

on:
  workflow_run:
    workflows:
      - Terraform
    types: 
      - completed
    branches:
      - master
    
jobs:
  mysql:
    name: 'Ansible'
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: terrafrom.yml
          workflow_conclusion: success
          name: terraform

      - id: host
        env:
          SSH: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            host=$(grep "apache_endpoint" terraform.log | awk -F  ":" '{print $1}' )
            host=${host//'apache_endpoint = "'}
            host=${host//'"'}
            echo $host >> apache/hosts
            cat apache/hosts
            echo "$SSH" > ansible/key.pem
            chmod 400 apache/key.pem
            cat apache/key.pem

      - name: Install Apache
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: 'apache/deploy.yml'
          inventoryFile: 'apache/hosts'
          keyFile: 'apache/key.pem'

      